#!/usr/bin/env python
"""
Run a single replica simulation from a config file.

This script is used for both local testing and SLURM cluster execution.
It loads a configuration JSON file and runs the complete simulation pipeline:
1. Equilibration (with reactions disabled)
2. Production run (with reactions enabled)

Usage:
    python run_replica.py --config path/to/config.json
    python run_replica.py --config path/to/config.json --skip-equilibration
    python run_replica.py --config path/to/config.json --equilibration-steps 20000

For cluster execution, this script is called by the SLURM job array script
generated by EnsembleSimulation.generate_slurm_scripts().
"""

import argparse
import os
import sys
import time

# Import the simulation module
try:
    import agglomeration_simulation as sim
except ImportError:
    # Try adding current directory to path
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import agglomeration_simulation as sim


def main():
    parser = argparse.ArgumentParser(
        description="Run a single replica simulation from a config file.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python run_replica.py --config configs/config_000.json
  python run_replica.py --config configs/config_000.json --equilibration-steps 20000
  python run_replica.py --config configs/config_000.json --skip-equilibration
        """
    )
    
    parser.add_argument(
        "--config", 
        required=True, 
        help="Path to configuration JSON file"
    )
    parser.add_argument(
        "--skip-equilibration", 
        action="store_true",
        help="Skip equilibration step (use random initial positions)"
    )
    parser.add_argument(
        "--equilibration-steps", 
        type=int, 
        default=10000,
        help="Number of equilibration steps (default: 10000)"
    )
    
    args = parser.parse_args()
    
    # Check config file exists
    if not os.path.exists(args.config):
        print(f"Error: Config file not found: {args.config}")
        sys.exit(1)
    
    # Record start time
    start_time = time.time()
    
    print("=" * 60)
    print("REPLICA SIMULATION")
    print("=" * 60)
    print(f"Config file: {args.config}")
    print(f"Equilibration: {'SKIP' if args.skip_equilibration else f'{args.equilibration_steps} steps'}")
    print("=" * 60)
    
    # Load configuration
    try:
        config = sim.SimulationConfig.load_json(args.config)
    except Exception as e:
        print(f"Error loading config: {e}")
        sys.exit(1)
    
    print(f"\nOutput file: {config.output_file}")
    print(f"RNG seed: {config.rng_seed}")
    print(f"Particles: {config.n_qt} Qt + {config.n_ft} Ft")
    print(f"Steps: {config.n_steps}")
    
    # Create output directory if needed
    output_dir = os.path.dirname(config.output_file)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
    
    # Run equilibration
    if args.skip_equilibration:
        print("\nSkipping equilibration (using random positions)...")
        pos_qt, pos_ft = None, None
    else:
        print(f"\nRunning equilibration ({args.equilibration_steps} steps)...")
        try:
            pos_qt, pos_ft = sim.equilibrate_system(config, n_steps=args.equilibration_steps)
        except Exception as e:
            print(f"Error during equilibration: {e}")
            sys.exit(1)
    
    # Create system and simulation
    print("\nSetting up production simulation...")
    try:
        system = sim.create_system(config)
        simulation = sim.create_simulation(system, config)
        sim.place_particles(simulation, config, positions_qt=pos_qt, positions_ft=pos_ft)
    except Exception as e:
        print(f"Error setting up simulation: {e}")
        sys.exit(1)
    
    # Run production
    print("\nRunning production simulation...")
    try:
        sim.run_simulation(simulation, config)
    except Exception as e:
        print(f"Error during simulation: {e}")
        sys.exit(1)
    
    # Record end time
    elapsed = time.time() - start_time
    
    print("\n" + "=" * 60)
    print("SIMULATION COMPLETE")
    print("=" * 60)
    print(f"Output: {config.output_file}")
    print(f"Elapsed time: {elapsed/60:.1f} minutes")
    print("=" * 60)
    
    # Verify output file was created
    if os.path.exists(config.output_file):
        size_mb = os.path.getsize(config.output_file) / (1024 * 1024)
        print(f"✓ Output file created ({size_mb:.1f} MB)")
    else:
        print("Warning: Output file was not created!")
        sys.exit(1)


if __name__ == "__main__":
    main()
