#!/usr/bin/env python
"""
Run a single replica simulation from a config file.

Used for both local testing and SLURM cluster execution. Loads a configuration
JSON and runs the full pipeline (equilibration with reactions disabled, then the
production run) via qtft.run_one().

Usage:
    python scripts/run_replica.py --config path/to/config.json
    python scripts/run_replica.py --config path/to/config.json --skip-equilibration
    python scripts/run_replica.py --config path/to/config.json --equilibration-steps 20000

For cluster execution this script is invoked by the SLURM job-array script
generated by EnsembleSimulation.generate_slurm_scripts().
"""

import argparse
import os
import sys
import time

# Make the qtft package importable when run as `python scripts/run_replica.py`.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import qtft


def main():
    parser = argparse.ArgumentParser(
        description="Run a single replica simulation from a config file.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python scripts/run_replica.py --config configs/config_000.json
  python scripts/run_replica.py --config configs/config_000.json --equilibration-steps 20000
  python scripts/run_replica.py --config configs/config_000.json --skip-equilibration
        """
    )

    parser.add_argument(
        "--config",
        required=True,
        help="Path to configuration JSON file"
    )
    parser.add_argument(
        "--skip-equilibration",
        action="store_true",
        help="Skip equilibration step (use random initial positions)"
    )
    parser.add_argument(
        "--equilibration-steps",
        type=int,
        default=10000,
        help="Number of equilibration steps (default: 10000)"
    )

    args = parser.parse_args()

    # Check config file exists
    if not os.path.exists(args.config):
        print(f"Error: Config file not found: {args.config}")
        sys.exit(1)

    # Record start time
    start_time = time.time()

    print("=" * 60)
    print("REPLICA SIMULATION")
    print("=" * 60)
    print(f"Config file: {args.config}")
    print(f"Equilibration: {'SKIP' if args.skip_equilibration else f'{args.equilibration_steps} steps'}")
    print("=" * 60)

    # Load configuration
    try:
        config = qtft.SimulationConfig.load_json(args.config)
    except Exception as e:
        print(f"Error loading config: {e}")
        sys.exit(1)

    print(f"\nOutput file: {config.output_file}")
    print(f"RNG seed: {config.rng_seed}")
    print(f"Particles: {config.n_qt} Qt + {config.n_ft} Ft")
    if config.phases:
        print(f"Phases: {len(config.phases)} "
              f"({', '.join(p.name for p in config.phases)}); "
              f"total steps: {config.effective_n_steps}")
    else:
        print(f"Steps: {config.n_steps}")

    # Run the full single-replica pipeline (output dir, equilibration, build,
    # place, production) via the shared run_one() entry point.
    if args.skip_equilibration:
        print("\nSkipping equilibration (using random positions)...")
    else:
        print(f"\nRunning equilibration ({args.equilibration_steps} steps)...")
    try:
        qtft.run_one(
            config,
            equilibration_steps=args.equilibration_steps,
            skip_equilibration=args.skip_equilibration,
        )
    except Exception as e:
        print(f"Error during simulation: {e}")
        sys.exit(1)

    # Record end time
    elapsed = time.time() - start_time

    print("\n" + "=" * 60)
    print("SIMULATION COMPLETE")
    print("=" * 60)
    print(f"Elapsed time: {elapsed/60:.1f} minutes")
    print("=" * 60)

    # Verify output file(s) were created. Phased runs write one trajectory per phase
    # (config.output_file itself is never written), so check the per-phase files.
    expected_files = config.phase_output_files if config.phases else [config.output_file]
    all_ok = True
    for f in expected_files:
        if os.path.exists(f):
            size_mb = os.path.getsize(f) / (1024 * 1024)
            print(f"✓ Output file created: {f} ({size_mb:.1f} MB)")
        else:
            print(f"Warning: Output file was not created: {f}")
            all_ok = False
    if not all_ok:
        sys.exit(1)


if __name__ == "__main__":
    main()
